version = 0.1
[default.deploy.parameters]
stack_name = "crimsondb"
resolve_s3 = true
s3_prefix = "crimsondb"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
